# **Avance 7**

## *WACC*

Este notebook procurará abarcar todos los temas para poder calcular el WACC aproximado de una acción

El WACC tiene la siguiente formula = Kd*(1-T)*d% + Ke*e%, donde:
* Kd = costo de la deuda (costo de proveedores, creditos de corto y largo plazo)
* (1-T) = intereses, la deuda pone a pagar menos intereses (escudo fiscal, T = 33% para Colombia)
* d% = proporción de la deuda sobre activo
* Ke = costo del patrimonio (acciones preferentes, utilidades retenidas y emision de acciones) o capital propio
* e% = proporcion del patrimonio sobre el activo

Vamos a ver como calcular cada una de estas componentes, pero hay que tener en cuenta los siguientes valores para poder calcular lo requerido en Kd y Ke:
* Km = tasa del mercado
* Kf = tasa libre de riesgo

## Km

Informacion del sector/indice de la accion (KM)

In [7]:
import pandas as pd
import yfinance as yf
from datetime import datetime

In [5]:
!pip install yfinance

Requirement already satisfied: yfinance in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (0.2.12)
Requirement already satisfied: pandas>=1.3.0 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (1.5.3)
Requirement already satisfied: numpy>=1.16.5 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (1.23.5)
Requirement already satisfied: requests>=2.26 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (2.28.2)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (4.9.2)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (1.4.4)
Requirement already satisfied: pytz>=2022.5 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (2022.7.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (2.3.5)
Requirement already satisfied: cryptography>=3.3.2 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (39.0.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (4.11.2)
Requirement already satisfied: html5lib>=1.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.4)
Requirement already satisfied: cffi>=1.12 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from cryptography>=3.3.2->yfinance) (1.15.1)
Requirement already satisfied: six>=1.9 in c:\users\usuario\appdata\roaming\python\python311\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\usuario\appdata\roaming\python\python311\site-packages (from pandas>=1.3.0->yfinance) (2.8.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.26->yfinance) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.26->yfinance) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.26->yfinance) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.26->yfinance) (2022.12.7)
Requirement already satisfied: pycparser in c:\users\usuario\appdata\local\programs\python\python311\lib\site-packages (from cffi>=1.12->cryptography>=3.3.2->yfinance) (2.21)

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [10]:
indice_sector = yf.Ticker("^DJT") #el ^ indica cualquier indice en yahoo-finance

inicio = datetime(2021, 1, 1)
fin = datetime(2022, 10, 31)

df = indice_sector.history(start = inicio, end = fin)
df #nos interesa la columna 'close

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2021-01-04 00:00:00-05:00,12513.820312,12537.419922,12151.410156,12230.030273,142910000,0.0,0.0
2021-01-05 00:00:00-05:00,12215.589844,12431.730469,12202.080078,12359.230469,111370000,0.0,0.0
2021-01-06 00:00:00-05:00,12401.799805,12782.059570,12381.259766,12706.320312,133340000,0.0,0.0
2021-01-07 00:00:00-05:00,12739.059570,12867.639648,12716.080078,12811.389648,105940000,0.0,0.0
2021-01-08 00:00:00-05:00,12858.669922,12995.290039,12825.290039,12875.660156,111590000,0.0,0.0
...,...,...,...,...,...,...,...
2022-10-24 00:00:00-04:00,12728.120117,13099.629883,12728.120117,13066.160156,119470000,0.0,0.0
2022-10-25 00:00:00-04:00,13055.280273,13310.330078,13055.280273,13246.660156,116470000,0.0,0.0
2022-10-26 00:00:00-04:00,13300.790039,13611.179688,13169.940430,13427.030273,117510000,0.0,0.0
2022-10-27 00:00:00-04:00,13466.440430,13616.790039,13337.009766,13369.089844,97870000,0.0,0.0
2022-10-28 00:00:00-04:00,13406.599609,13584.980469,13256.500000,13574.980469,91640000,0.0,0.0

In [11]:
df_km = pd.DataFrame()
df_km['Valor'] = df['Close']
df_km['Porcentaje'] = 0
df_km

                                  Valor  Porcentaje
Date
2021-01-04 00:00:00-05:00  12230.030273           0
2021-01-05 00:00:00-05:00  12359.230469           0
2021-01-06 00:00:00-05:00  12706.320312           0
2021-01-07 00:00:00-05:00  12811.389648           0
2021-01-08 00:00:00-05:00  12875.660156           0
...                                 ...         ...
2022-10-24 00:00:00-04:00  13066.160156           0
2022-10-25 00:00:00-04:00  13246.660156           0
2022-10-26 00:00:00-04:00  13427.030273           0
2022-10-27 00:00:00-04:00  13369.089844           0
2022-10-28 00:00:00-04:00  13574.980469           0

[460 rows x 2 columns]

In [36]:
df_km['Valor'][459]

13574.98046875

In [44]:
import math

contador = 1
p_diario = 0
p_anual = 0

for x,y in df_km.iterrows():
    if contador == 460:
        p_diario = p_diario/contador
        print("Promedio diario:", p_diario*100)
        p_anual = p_diario*252 #este es el km a utilizar
        print("Promedio anual:",p_anual*100)
        contador=999999
    else:
        operacion = math.log(df_km['Valor'][contador]/df_km['Valor'][contador-1])
        df_km['Porcentaje'][contador] = operacion
        contador = contador + 1
        p_diario = p_diario + operacion

Promedio diario: 0.02268130478574696
Promedio anual: 5.7156888060082345

In [45]:
df_km

                                  Valor  Porcentaje
Date
2021-01-04 00:00:00-05:00  12230.030273    0.000000
2021-01-05 00:00:00-05:00  12359.230469    0.010509
2021-01-06 00:00:00-05:00  12706.320312    0.027696
2021-01-07 00:00:00-05:00  12811.389648    0.008235
2021-01-08 00:00:00-05:00  12875.660156    0.005004
...                                 ...         ...
2022-10-24 00:00:00-04:00  13066.160156    0.028995
2022-10-25 00:00:00-04:00  13246.660156    0.013720
2022-10-26 00:00:00-04:00  13427.030273    0.013524
2022-10-27 00:00:00-04:00  13369.089844   -0.004325
2022-10-28 00:00:00-04:00  13574.980469    0.015283

[460 rows x 2 columns]

## Kf

Esta tasa libre de riesgo depende de la situación de cada empresa.

Para el caso de FedEx (ejemplo trabajado en todos los notebooks), al ser una empresa muy grande no va a tener riesgo proximo de quebrarse, por lo cual puede pedir prestamos por 10 años (TES=10). Valor, según el grupo AVAL, de un TES de 10 años es del 11% (esto puede cambiar)

In [52]:
kf = 0.11

## Kd

## Ke